[versions]
androidx_compat = "1.6.1"
androidx_constraintlayout = "2.1.4"
tomtom_sdk = "0.37.0"

[libraries]
locationProvider = { module = "com.tomtom.sdk.location:provider-android", version.ref = "tomtom_sdk" }
locationSimulation = { module = "com.tomtom.sdk.location:provider-simulation", version.ref = "tomtom_sdk" }
locationMapmatched = { module = "com.tomtom.sdk.location:provider-map-matched", version.ref = "tomtom_sdk" }
mapsDisplay = { module = "com.tomtom.sdk.maps:map-display", version.ref = "tomtom_sdk" }
navigationOnline = { module = "com.tomtom.sdk.navigation:navigation-online", version.ref = "tomtom_sdk" }
navigationUi = { module = "com.tomtom.sdk.navigation:ui", version.ref = "tomtom_sdk" }
routePlannerOnline = { module = "com.tomtom.sdk.routing:route-planner-online", version.ref = "tomtom_sdk" }
routeReplannerOnline = { module = "com.tomtom.sdk.navigation:route-replanner-online", version.ref = "tomtom_sdk" }
androidXCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx_compat" }
androidXConstraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx_constraintlayout" }

[bundles]
androidCommon = ["androidXCompat", "androidXConstraintLayout"]

[plugins]
androidApplication = { id = "com.android.application", version = "7.4.2" }
androidLibrary = { id = "com.android.library", version = "7.4.2" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version = "1.8.22"}

