[versions]
androidx_compat = "1.6.1"
androidx_constraintlayout = "2.1.4"
androidx_activityCompose = "1.8.2"
androidx_composeBom = "2024.03.00"
default_world_map = "45424"
tomtom_sdk = "1.8.0"

[libraries]
dataProviderOffline = { module = "com.tomtom.sdk.maps:data-provider-offline", version.ref = "tomtom_sdk" }
ndsStore = {module = "com.tomtom.sdk.datamanagement:nds-store", version.ref = "tomtom_sdk"}
ndsStoreUpdater = {module = "com.tomtom.sdk.datamanagement:nds-store-updater", version.ref = "tomtom_sdk"}
featureToggle = { module = "com.tomtom.sdk:feature-toggle", version.ref = "tomtom_sdk" }
locationProvider = { module = "com.tomtom.sdk.location:provider-android", version.ref = "tomtom_sdk" }
locationSimulation = { module = "com.tomtom.sdk.location:provider-simulation", version.ref = "tomtom_sdk" }
locationMapmatched = { module = "com.tomtom.sdk.location:provider-map-matched", version.ref = "tomtom_sdk" }
mapsDisplay = { module = "com.tomtom.sdk.maps:map-display", version.ref = "tomtom_sdk" }
navigationUi = { module = "com.tomtom.sdk.navigation:ui", version.ref = "tomtom_sdk" }
navigationOffline = { module = "com.tomtom.sdk.navigation:navigation-offline", version.ref = "tomtom_sdk" }
routeReplannerOffline = { module = "com.tomtom.sdk.routing:route-planner-offline", version.ref = "tomtom_sdk" }
styleProviderOffline = { module = "com.tomtom.sdk.maps:style-provider-offline", version.ref = "tomtom_sdk" }
defaultMap = { module = "com.tomtom.sdk.datamanagement.nds:default-world-map", version.ref = "default_world_map" }
navigationOnline = { module = "com.tomtom.sdk.navigation:navigation-online", version.ref = "tomtom_sdk" }
routePlannerOnline = { module = "com.tomtom.sdk.routing:route-planner-online", version.ref = "tomtom_sdk" }
routeReplannerOnline = { module = "com.tomtom.sdk.navigation:route-replanner-online", version.ref = "tomtom_sdk" }
androidXCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx_compat" }
androidXConstraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx_constraintlayout" }
androidxActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx_activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx_composeBom" }
compose-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class" }
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
compose-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-viewbinding = { group = "androidx.compose.ui", name = "ui-viewbinding" }

[bundles]
androidCommon = [
    "androidXCompat",
    "androidXConstraintLayout",
    "androidxActivityCompose",
]

androidCompose = [
    "compose-graphics",
    "compose-material-icons-core",
    "compose-material-icons-extended",
    "compose-material3",
    "compose-material3-window-size",
    "compose-runtime-livedata",
    "compose-tooling-preview",
    "compose-ui",
    "compose-viewbinding",
]

[plugins]
androidApplication = { id = "com.android.application", version = "8.5.0" }
androidLibrary = { id = "com.android.library", version = "8.5.0" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version = "1.8.22"}

